In [4]:
import pandas as pd
import scattertext as st
import spacy
from pprint import pprint

In [5]:
convention_df = st.SampleCorpora.ConventionData2012.get_data()
convention_df.head()

      party         speaker                                               text
0  democrat    BARACK OBAMA  Thank you. Thank you. Thank you. Thank you so ...
1  democrat  MICHELLE OBAMA  Thank you so much. Tonight, I am so thrilled a...
2  democrat  RICHARD DURBIN  Thank you. It is a singular honor to be here t...
3  democrat    JOSEPH BIDEN  Hey, Delaware. \nAnd my favorite Democrat, Jil...
4  democrat      JILL BIDEN  Hello. \nThank you, Angie. I'm so proud of how...

In [6]:
ted_talks = pd.read_json('interactive-visual/ted-talks.json', orient='records')
ted_talks.head()

,AllPunc,Analytic,Apostro,Authentic,Clout,Colon,Comma,Dash,Dic,Exclam,...,title,transcript,transcript_url,url,verb,views,we,work,year_filmed,you
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,"\r\r\rThank you so much, Chris.\rAnd it's trul...",http://www.ted.com/talks/view/id/1/transcript?...,http://www.ted.com/talks/view/id/1,16.26,3177001.0,1.62,2.37,2006,2.28
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,"\r\r\rIn terms of invention,\rI'd like to tell...",http://www.ted.com/talks/view/id/2/transcript?...,http://www.ted.com/talks/view/id/2,17.19,1379328.0,2.79,3.13,2006,2.16
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,"\r\r\rA public, Dewey long ago observed,\ris c...",http://www.ted.com/talks/view/id/3/transcript?...,http://www.ted.com/talks/view/id/3,15.56,790536.0,2.00,4.23,2005,1.40
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,"\r\r\rI want to start off by saying, Houston, ...",http://www.ted.com/talks/view/id/4/transcript?...,http://www.ted.com/talks/view/id/4,18.47,1985119.0,2.68,2.62,2006,1.58
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,None,"\r\r\rWhat I want to talk about is, as backgro...",http://www.ted.com/talks/view/id/5/transcript?...,http://www.ted.com/talks/view/id/5,19.70,859487.0,2.59,2.22,2002,2.38

In [8]:
nlp = spacy.load('en')
corpus = st.CorpusFromPandas(ted_talks, category_col='event', text_col='transcript', nlp=nlp).build()

In [9]:
print(list(corpus.get_scaled_f_scores_vs_background().index[:10]))

['actually', 'imagine', 'going', 'wo', 'brain', 'basically', 'somebody', 'everybody', 'really', 'so']

In [ ]:
html = st.produce_scattertext_explorer(corpus.get_unigram_corpus().compact(st.ClassPercentageCompactor(term_count=2, term_ranker=st.OncePerDocFrequencyRanker)),
            category='TED2018',
            category_name='TED2018',
            not_category_name='Other',
            width_in_pixels=1000)
#             ,metadata=ted_talks['speaker'])

In [12]:
open("TED2018-Visualization.html", 'wb').write(html.encode('utf-8'))

44559707